version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3 # NodeLTS as of 06/2018
    environment:
      NODE_ENV: "production" # Won't install anything from devDependencies
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: yarn install
      - run: 
          name: Build alpha.australia.gov.au
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./deploy
            - ./public
  deploy:
    docker:
      - image: govau/cf-cli
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploying to cloud.gov.au
          command: |
            cf login -a api.system.y.cld.gov.au -o dta -s $CF_STAG_SPACE -u $CF_STAG_USER -p $CF_STAG_PASS
            cf zero-downtime-push ausgov -f ./deploy/stag-manifest.yml
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - deploy:
          requires:
            - build