version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: yarn --version
      - run: 
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install cf CLI
          command: wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          command: echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          command: sudo apt-get update && sudo apt-get install cf-cli
          command: cf-cli --version


