version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - run: 
          name: Node version check
          command: |
            node --version
            npm --version
            yarn --version
      - run: 
          name: Install dependencies
          command: yarn install
      - run:
          name: Install cf CLI
          command: |
            wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            sudo apt-get update && sudo apt-get install cf-cli
            cf-cli --version


