version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run: sudo apt-get update && sudo apt-get install apt-transport-https yarn
      - run: yarn --version
      - run: yarn install
