version: 2
jobs:
  build-ausgov:
    docker:
      - image: circleci/node:8.11.3 # NodeLTS as of 06/2018
    machine:
      pre:
        - mkdir ~/.yarn-cache
    dependencies:
      cache_directories:
        - ~/.yarn-cache
    environment:
      NODE_ENV: "production" # Won't install anything from devDependencies.
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - m2-yarn-packages-{{ checksum "yarn.lock" }}-circle-{{ .Environment.CIRCLE_SHA1 }}
      - run: 
          name: Install dependencies
          command: yarn install --cache-folder ~/.yarn-cache
      - save_cache:
          name: Save Yarn Package Cache
          key: m2-yarn-packages-{{ checksum "yarn.lock" }}-circle-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules/
      - run: 
          name: Build alpha.australia.gov.au
          command: yarn build
      - persist_to_workspace:
          root: ~/project # /home/circleci/project
          paths:
            - ./deploy
            - ./public
  deploy-stag:
    docker:
      - image: govau/cf-cli
    steps:
      - attach_workspace:
          at: ~/project # /home/root/project
      - run:
          name: Deploying to cloud.gov.au
          command: |
            cf login -a api.system.y.cld.gov.au -o dta -s $CF_STAG_SPACE -u $CF_STAG_USER -p $CF_STAG_PASS
            cf zero-downtime-push ausgov -f ./deploy/stag-manifest.yml
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-ausgov:
          filters:
            branches:
              only:
                - issue/34-Resolve-circleci-asset-cache # Testing
      - deploy-stag:
          requires:
            - build-ausgov