---
applications:
- name: ausgov
  buildpack: nodejs_buildpack
  memory: 128M
  instances: 1
  path: ./
  env: 
    OPTIMIZE_MEMORY: true
    NODE_ENV: production
routes:
- route: alpha.australia.gov.au
